### ISSUE TITLE
SlackEventListener is not a constructor

### ISSUE THREAD

**Issue by lesyk** [suttna/botbuilder-slack-extension#7]
<img width="919" alt="screen shot 2017-11-15 at 12 55 02 pm" src="https://user-images.githubusercontent.com/818588/32834830-4a0f31cc-ca04-11e7-9a9d-7b0f141a3357.png">

`botbuilder-slack-extension` is in my `npm_modules` folder.

**Comment by bilby91** [comment]
Repository deprecated in favor of https://github.com/suttna/botbuilder-slack
